package de.muenchen.animad.admin.administration.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.animad.admin.administration.service.gen.domain.Keeper_;
import de.muenchen.animad.admin.administration.service.gen.services.event.Keeper_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Keeper_EventListener.
 */
@Service
public class Keeper_EventServiceImpl implements Keeper_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Keeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Keeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Keeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Keeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Keeper_ parent, Object linked) {
		// Add your logic here.
	}
}
