package de.muenchen.animad.admin.administration.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.animad.admin.administration.service.gen.domain.Zookeeper_;
import de.muenchen.animad.admin.administration.service.gen.services.event.Zookeeper_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Zookeeper_EventListener.
 */
@Service
public class Zookeeper_EventServiceImpl implements Zookeeper_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Zookeeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Zookeeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Zookeeper_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Zookeeper_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Zookeeper_ parent, Object linked) {
		// Add your logic here.
	}
}
